- name: Configure eth1 (private network)
  template:
    src: templates/ifcfg-eth1.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1
  register: ifcfg_eth1

- name: Enable eth1 (private network)
  service:
    name: network
    state: restarted
  when: ifcfg_eth1.changed

- name: Change eth1 To Internal Zone In Firewalld
  firewalld:
    zone: internal
    interface: eth1
    permanent: true
    state: enabled
